// <auto-generated />
using Cinema.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Data.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Christopher",
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Quentin",
                            LastName = "Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Hayao",
                            LastName = "Miyazaki"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Greta",
                            LastName = "Gerwig"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearReleased")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            DirectorId = 1,
                            GenreId = 1,
                            Likes = 194,
                            Poster = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            Title = "Inception",
                            YearReleased = 2010
                        },
                        new
                        {
                            Id = 2,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            DirectorId = 1,
                            GenreId = 1,
                            Likes = 827,
                            Poster = "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Interstellar",
                            YearReleased = 2014
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker, a criminal mastermind bent on chaos.",
                            DirectorId = 1,
                            GenreId = 4,
                            Likes = 963,
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
                            Title = "The Dark Knight",
                            YearReleased = 2008
                        },
                        new
                        {
                            Id = 4,
                            Description = "The story of Oskar Schindler, a German businessman who saved Jewish lives during the Holocaust.",
                            DirectorId = 2,
                            GenreId = 2,
                            Likes = 743,
                            Poster = "https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_.jpg",
                            Title = "Schindler's List",
                            YearReleased = 1993
                        },
                        new
                        {
                            Id = 5,
                            Description = "Scientists clone dinosaurs and create a theme park that quickly spirals out of control.",
                            DirectorId = 2,
                            GenreId = 1,
                            Likes = 665,
                            Poster = "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_.jpg",
                            Title = "Jurassic Park",
                            YearReleased = 1993
                        },
                        new
                        {
                            Id = 6,
                            Description = "Captain Miller leads a mission to rescue a paratrooper during WWII.",
                            DirectorId = 2,
                            GenreId = 4,
                            Likes = 886,
                            Poster = "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Saving Private Ryan",
                            YearReleased = 1998
                        },
                        new
                        {
                            Id = 7,
                            Description = "The lives of two mob hitmen, a boxer, and others intertwine in four tales of violence and redemption.",
                            DirectorId = 3,
                            GenreId = 2,
                            Likes = 934,
                            Poster = "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Pulp Fiction",
                            YearReleased = 1994
                        },
                        new
                        {
                            Id = 8,
                            Description = "A freed slave sets out to rescue his wife with the help of a German bounty hunter.",
                            DirectorId = 3,
                            GenreId = 4,
                            Likes = 578,
                            Poster = "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_.jpg",
                            Title = "Django Unchained",
                            YearReleased = 2012
                        },
                        new
                        {
                            Id = 9,
                            Description = "A former assassin seeks revenge on the team that betrayed her.",
                            DirectorId = 3,
                            GenreId = 4,
                            Likes = 442,
                            Poster = "https://m.media-amazon.com/images/M/MV5BZmMyYzJlZmYtY2I3NC00NjAyLTkyZWItZjdjZDI1YTYyYTEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Kill Bill: Vol. 1",
                            YearReleased = 2003
                        },
                        new
                        {
                            Id = 10,
                            Description = "A young girl enters a magical world and must find her way back.",
                            DirectorId = 4,
                            GenreId = 3,
                            Likes = 792,
                            Poster = "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Spirited Away",
                            YearReleased = 2001
                        },
                        new
                        {
                            Id = 11,
                            Description = "Two girls discover magical creatures in the countryside.",
                            DirectorId = 4,
                            GenreId = 3,
                            Likes = 311,
                            Poster = "https://m.media-amazon.com/images/M/MV5BYWM3MDE3YjEtMzIzZC00ODE5LTgxNTItNmUyMTBkM2M2NmNiXkEyXkFqcGc@._V1_.jpg",
                            Title = "My Neighbor Totoro",
                            YearReleased = 1988
                        },
                        new
                        {
                            Id = 12,
                            Description = "A young warrior gets caught in a struggle between forest gods and humans.",
                            DirectorId = 4,
                            GenreId = 3,
                            Likes = 667,
                            Poster = "https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Princess Mononoke",
                            YearReleased = 1997
                        },
                        new
                        {
                            Id = 13,
                            Description = "A teenager navigates love, family, and identity during her final year of high school.",
                            DirectorId = 5,
                            GenreId = 2,
                            Likes = 249,
                            Poster = "https://m.media-amazon.com/images/M/MV5BNjk5MzcyOWQtNzE1Mi00NzdmLTlkM2QtOTdjZThhMDc2Y2NjXkEyXkFqcGc@._V1_.jpg",
                            Title = "Lady Bird",
                            YearReleased = 2017
                        },
                        new
                        {
                            Id = 14,
                            Description = "The lives of the March sisters as they grow up in post-Civil War America.",
                            DirectorId = 5,
                            GenreId = 2,
                            Likes = 358,
                            Poster = "https://m.media-amazon.com/images/M/MV5BMWMzYjNiZWMtMDg4NS00MDgyLTk5MWItOTFmNjg4NzRhZmExXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Little Women",
                            YearReleased = 2019
                        },
                        new
                        {
                            Id = 15,
                            Description = "Barbie and Ken experience the real world on a journey of self-discovery.",
                            DirectorId = 5,
                            GenreId = 3,
                            Likes = 999,
                            Poster = "https://m.media-amazon.com/images/M/MV5BYjI3NDU0ZGYtYjA2YS00Y2RlLTgwZDAtYTE2YTM5ZjE1M2JlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Title = "Barbie",
                            YearReleased = 2023
                        });
                });

            modelBuilder.Entity("Cinema.Data.Models.Movie", b =>
                {
                    b.HasOne("Cinema.Data.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Data.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Cinema.Data.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Cinema.Data.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
